USE master
GO

CREATE DATABASE MainDBM
GO

USE MainDBM
GO

CREATE TABLE Customer (
	CustId INT NOT NULL IDENTITY PRIMARY KEY,
	FirstName VARCHAR(100) NOT NULL,
	LastName VARCHAR(100),
	Email VARCHAR(100),
	Address1 VARCHAR(100),
	Address2 VARCHAR(100),
	City VARCHAR(100),
	CustState VARCHAR(100), --state is a reserved keyword
	PhoneNumber VARCHAR(100),
	Note VARCHAR(MAX),
	DateEntered DateTime
);
GO

CREATE TABLE Inventory (
	InventoryId INT NOT NULL IDENTITY PRIMARY KEY,
	InvenName VARCHAR(100) NOT NULL,
	Descript VARCHAR(MAX),
	BuyPrice DECIMAL NOT NULL,
	SalePrice DECIMAL NOT NULL
);
GO

CREATE TABLE Receipt (
	ReceiptId INT NOT NULL IDENTITY PRIMARY KEY,
	CustId INT FOREIGN KEY REFERENCES Customer(CustId),
	SaleDate DATETIME NOT NULL
);
GO

CREATE TABLE ReceiptDetail(
	InventoryId INT FOREIGN KEY REFERENCES Inventory(InventoryId),
	ReceiptId INT FOREIGN KEY REFERENCES Receipt(ReceiptId),
	Quantity INT NOT NULL
);

CREATE TABLE Users(
	UserId INT NOT NULL IDENTITY PRIMARY KEY,
	DateCreated DateTime NOT NULL,
	Username VARCHAR(100) NOT NULL,
	Pwd VARCHAR(MAX) NOT NULL,
	TempPassword VARCHAR(MAX),
	AuthLevel INT NOT NULL
);

CREATE TABLE Errors(
	ErrorId INT NOT NULL IDENTITY PRIMARY KEY,
	ErrorDate DateTime NOT NULL,
	ErrorMessage VARCHAR(MAX) NOT NULL, 
	StackTrace VARCHAR(MAX)
);
